# --- Build Stage ---
FROM golang:1.24.7-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /src/build/onepacd /src/cmd/onepacd

FROM alpine:3.22.2

WORKDIR /

COPY --from=builder /src/build/onepacd /opt/run/onepacd
COPY --from=builder /src/app/onepacd/config.yaml /opt/run/config.yaml

EXPOSE 8080

ENTRYPOINT ["/opt/run/onepacd", "run", "-c", "/opt/run/config.yaml"]