// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/blockchain.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNetworkHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkHealthRequest) Reset() {
	*x = GetNetworkHealthRequest{}
	mi := &file_api_blockchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkHealthRequest) ProtoMessage() {}

func (x *GetNetworkHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_blockchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkHealthRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkHealthRequest) Descriptor() ([]byte, []int) {
	return file_api_blockchain_proto_rawDescGZIP(), []int{0}
}

func (x *GetNetworkHealthRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetNetworkHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkHealthResponse) Reset() {
	*x = GetNetworkHealthResponse{}
	mi := &file_api_blockchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkHealthResponse) ProtoMessage() {}

func (x *GetNetworkHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_blockchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkHealthResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkHealthResponse) Descriptor() ([]byte, []int) {
	return file_api_blockchain_proto_rawDescGZIP(), []int{1}
}

func (x *GetNetworkHealthResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_blockchain_proto protoreflect.FileDescriptor

const file_api_blockchain_proto_rawDesc = "" +
	"\n" +
	"\x14api/blockchain.proto\x12\x03api\")\n" +
	"\x17GetNetworkHealthRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"*\n" +
	"\x18GetNetworkHealthResponse\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02idB3Z1github.com/frimin/1pactus-react/backend/proto/apib\x06proto3"

var (
	file_api_blockchain_proto_rawDescOnce sync.Once
	file_api_blockchain_proto_rawDescData []byte
)

func file_api_blockchain_proto_rawDescGZIP() []byte {
	file_api_blockchain_proto_rawDescOnce.Do(func() {
		file_api_blockchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_blockchain_proto_rawDesc), len(file_api_blockchain_proto_rawDesc)))
	})
	return file_api_blockchain_proto_rawDescData
}

var file_api_blockchain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_blockchain_proto_goTypes = []any{
	(*GetNetworkHealthRequest)(nil),  // 0: api.GetNetworkHealthRequest
	(*GetNetworkHealthResponse)(nil), // 1: api.GetNetworkHealthResponse
}
var file_api_blockchain_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_blockchain_proto_init() }
func file_api_blockchain_proto_init() {
	if File_api_blockchain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_blockchain_proto_rawDesc), len(file_api_blockchain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_blockchain_proto_goTypes,
		DependencyIndexes: file_api_blockchain_proto_depIdxs,
		MessageInfos:      file_api_blockchain_proto_msgTypes,
	}.Build()
	File_api_blockchain_proto = out.File
	file_api_blockchain_proto_goTypes = nil
	file_api_blockchain_proto_depIdxs = nil
}
